import Product from "../../types/Product";

export const ProductTestArray:Product[] = [
    {
        id: 1,
        name: "Procesador AMD Ryzen 5 7600X",
        description: "CPU de 6 núcleos y 12 hilos con una velocidad de hasta 5.3 GHz.",
        image: "https://example.com/ryzen5-7600x.jpg",
        price: 249.99,
        discount: 10, // 10% de descuento
        rate: 4.2,
        opinions: 1200,
        categoryID: 1,
      },
      {
        id: 2,
        name: "Tarjeta Gráfica AMD Radeon RX 7800XT",
        description: "GPU potente con 16GB GDDR6 para gaming en 1440p y 4K.",
        image: "https://example.com/rx7800xt.jpg",
        price: 549.99,
        rate: 1.7,
        opinions: 800,
        categoryID: 2,
      },
      {
        id: 3,
        name: "Placa Base MSI B650 Tomahawk WiFi",
        description: "Placa base con socket AM5 y soporte para DDR5.",
        image: "https://example.com/msi-b650.jpg",
        price: 199.99,
        discount: 5,
        rate: 0.4,
        opinions: 450,
        categoryID: 3,
      },
      {
        id: 4,
        name: "Memoria RAM Corsair Vengeance 32GB (2x16GB) DDR5 6000MHz",
        description: "Kit de memoria de alto rendimiento con perfil XMP 3.0.",
        image: "https://example.com/vengeance32gb.jpg",
        price: 179.99,
        rate: 4.9,
        opinions: 950,
        categoryID: 4,
      },
      {
        id: 5,
        name: "SSD NVMe Kingston KC3000 1TB",
        description: "Unidad SSD ultrarrápida con velocidades de hasta 7000MB/s.",
        image: "https://example.com/kc3000-1tb.jpg",
        price: 119.99,
        discount: 15,
        rate: 0,
        opinions: 600,
        categoryID: 5,
      },
]